import type { CompetitionMeta } from '@/lib/ingestion/types';

/**
 * 36 competitions verified via live API-Football queries.
 * Ordered by tier (Tier 1 seeded first → Tier 6 last).
 *
 * Team IDs (Morocco men=31, Morocco women=14461, Wydad=968, Raja=976)
 * and player IDs (Hakimi=9) live in canonical-ids.ts — they are NOT
 * competitions and do not appear here.
 */
export const VERIFIED_COMPETITIONS: CompetitionMeta[] = [
  // ── Tier 1: FIFA World Cup 2026 + Qualifiers ──
  {
    id: 1,
    slug: 'world-cup',
    tier: 1,
    isWomen: false,
    isFeatured: true,
    isMoroccoFocus: false,
    displayPriority: 10,
  },
  {
    id: 29,
    slug: 'wc-qualifiers-africa',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 11,
  },
  {
    id: 32,
    slug: 'wc-qualifiers-europe',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 12,
  },
  {
    id: 31,
    slug: 'wc-qualifiers-concacaf',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 13,
  },
  {
    id: 34,
    slug: 'wc-qualifiers-south-america',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 14,
  },
  {
    id: 30,
    slug: 'wc-qualifiers-asia',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 15,
  },
  {
    id: 33,
    slug: 'wc-qualifiers-oceania',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 16,
  },
  {
    id: 37,
    slug: 'wc-qualifiers-intercontinental',
    tier: 1,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 17,
  },

  // ── Tier 2: Morocco men's domestic ──
  {
    id: 200,
    slug: 'botola-pro-1',
    tier: 2,
    isWomen: false,
    isFeatured: true,
    isMoroccoFocus: true,
    displayPriority: 20,
  },
  {
    id: 201,
    slug: 'botola-2',
    tier: 2,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: true,
    displayPriority: 21,
  },
  {
    id: 822,
    slug: 'coupe-du-trone',
    tier: 2,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: true,
    displayPriority: 22,
  },

  // ── Tier 3: Africa continental ──
  {
    id: 6,
    slug: 'afcon',
    tier: 3,
    isWomen: false,
    isFeatured: true,
    isMoroccoFocus: false,
    displayPriority: 30,
  },
  {
    id: 36,
    slug: 'afcon-qualifiers',
    tier: 3,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 31,
  },
  {
    id: 922,
    slug: 'wafcon',
    tier: 3,
    isWomen: true,
    isFeatured: true,
    isMoroccoFocus: false,
    displayPriority: 32,
  },
  {
    id: 12,
    slug: 'caf-champions-league',
    tier: 3,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 33,
  },
  {
    id: 20,
    slug: 'caf-confederation-cup',
    tier: 3,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 34,
  },

  // ── Tier 4: Top European leagues + UEFA club ──
  {
    id: 39,
    slug: 'premier-league',
    tier: 4,
    isWomen: false,
    isFeatured: true,
    isMoroccoFocus: false,
    displayPriority: 40,
  },
  {
    id: 140,
    slug: 'la-liga',
    tier: 4,
    isWomen: false,
    isFeatured: true,
    isMoroccoFocus: false,
    displayPriority: 41,
  },
  {
    id: 135,
    slug: 'serie-a',
    tier: 4,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 42,
  },
  {
    id: 78,
    slug: 'bundesliga',
    tier: 4,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 43,
  },
  {
    id: 61,
    slug: 'ligue-1',
    tier: 4,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 44,
  },
  {
    id: 2,
    slug: 'uefa-champions-league',
    tier: 4,
    isWomen: false,
    isFeatured: true,
    isMoroccoFocus: false,
    displayPriority: 45,
  },
  {
    id: 3,
    slug: 'uefa-europa-league',
    tier: 4,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 46,
  },
  {
    id: 848,
    slug: 'uefa-europa-conference-league',
    tier: 4,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 47,
  },

  // ── Tier 5: Women's European + UEFA women's ──
  {
    id: 44,
    slug: 'fa-wsl',
    tier: 5,
    isWomen: true,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 50,
  },
  {
    id: 142,
    slug: 'liga-f',
    tier: 5,
    isWomen: true,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 51,
  },
  {
    id: 139,
    slug: 'serie-a-women',
    tier: 5,
    isWomen: true,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 52,
  },
  {
    id: 82,
    slug: 'frauen-bundesliga',
    tier: 5,
    isWomen: true,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 53,
  },
  {
    id: 525,
    slug: 'uwcl',
    tier: 5,
    isWomen: true,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 54,
  },
  {
    id: 1191,
    slug: 'uefa-europa-cup-women',
    tier: 5,
    isWomen: true,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 55,
  },

  // ── Tier 6: MENA / Middle East top-flight men's ──
  {
    id: 186,
    slug: 'algeria-ligue-1',
    tier: 6,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 60,
  },
  {
    id: 202,
    slug: 'tunisia-ligue-1',
    tier: 6,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 61,
  },
  {
    id: 233,
    slug: 'egypt-premier-league',
    tier: 6,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 62,
  },
  {
    id: 203,
    slug: 'turkey-super-lig',
    tier: 6,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 63,
  },
  {
    id: 301,
    slug: 'uae-pro-league',
    tier: 6,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 64,
  },
  {
    id: 307,
    slug: 'saudi-pro-league',
    tier: 6,
    isWomen: false,
    isFeatured: false,
    isMoroccoFocus: false,
    displayPriority: 65,
  },
];

/**
 * Competitions from the plan (Part B, 60 total) that have NOT yet been
 * verified via live API queries. IDs are best-guesses or null (unknown).
 * Verified during Phase 4 cleanup or when those competitions come into season.
 */
export const UNVERIFIED_COMPETITION_NAMES: Record<string, number | null> = {
  'WAFCON Qualifiers': null,
  'Botola Pro Feminine': null,
  'Coupe du Trone Feminine': null,
  'UEFA Nations League': null,
  'UEFA Euro Qualifiers': null,
  'CAF Women Champions League': null,
  'African Football League': null,
  'FIFA Women World Cup 2027': null,
  'Women WC 2027 Qualifiers (all confederations)': null,
  'FIFA Club World Cup': null,
  'FIFA Women Club World Cup': null,
  'Olympics Football Men': null,
  'Olympics Football Women': null,
  'Arab Cup Men': null,
  'Arab Cup Women': null,
  'Premiere Ligue (France Women)': null,
};
