/**
 * FIFA World Cup 2026 official match schedule.
 * Source: FWC26 Match Schedule v17 (10 April 2026)
 * https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026
 *
 * All 104 matches with FIFA-assigned match numbers, dates, venues.
 * Group stage (M1-M72) uses 3-letter team codes.
 * Knockout (M73-M104) uses placeholder codes (1C, W74, RU101).
 *
 * All kickoff times are Eastern Time (ET) as printed on the PDF.
 * Sorted by fifaMatchNumber ascending.
 */

export interface WC2026Match {
  fifaMatchNumber: number;
  phase: 'group' | 'r32' | 'r16' | 'qf' | 'sf' | 'final' | 'third';
  groupLetter: string | null;
  date: string; // YYYY-MM-DD
  kickoffEt: string; // HH:MM
  homeSlot: string; // team code or placeholder
  awaySlot: string; // team code or placeholder
  venue: string; // full city name
}

export const WC_2026_SCHEDULE: WC2026Match[] = [
  // ── Group A: MEX, RSA, KOR, CZE ──────────────────────────────
  {
    fifaMatchNumber: 1,
    phase: 'group',
    groupLetter: 'A',
    date: '2026-06-11',
    kickoffEt: '15:00',
    homeSlot: 'MEX',
    awaySlot: 'RSA',
    venue: 'Mexico City',
  },
  {
    fifaMatchNumber: 2,
    phase: 'group',
    groupLetter: 'A',
    date: '2026-06-11',
    kickoffEt: '22:00',
    homeSlot: 'KOR',
    awaySlot: 'CZE',
    venue: 'Guadalajara',
  },
  {
    fifaMatchNumber: 25,
    phase: 'group',
    groupLetter: 'A',
    date: '2026-06-18',
    kickoffEt: '12:00',
    homeSlot: 'CZE',
    awaySlot: 'RSA',
    venue: 'Atlanta',
  },
  {
    fifaMatchNumber: 28,
    phase: 'group',
    groupLetter: 'A',
    date: '2026-06-18',
    kickoffEt: '21:00',
    homeSlot: 'MEX',
    awaySlot: 'KOR',
    venue: 'Guadalajara',
  },
  {
    fifaMatchNumber: 53,
    phase: 'group',
    groupLetter: 'A',
    date: '2026-06-24',
    kickoffEt: '21:00',
    homeSlot: 'CZE',
    awaySlot: 'MEX',
    venue: 'Mexico City',
  },
  {
    fifaMatchNumber: 54,
    phase: 'group',
    groupLetter: 'A',
    date: '2026-06-24',
    kickoffEt: '21:00',
    homeSlot: 'RSA',
    awaySlot: 'KOR',
    venue: 'Monterrey',
  },

  // ── Group B: CAN, BIH, QAT, SUI ──────────────────────────────
  {
    fifaMatchNumber: 3,
    phase: 'group',
    groupLetter: 'B',
    date: '2026-06-12',
    kickoffEt: '15:00',
    homeSlot: 'CAN',
    awaySlot: 'BIH',
    venue: 'Toronto',
  },
  {
    fifaMatchNumber: 8,
    phase: 'group',
    groupLetter: 'B',
    date: '2026-06-13',
    kickoffEt: '15:00',
    homeSlot: 'QAT',
    awaySlot: 'SUI',
    venue: 'San Francisco Bay Area',
  },
  {
    fifaMatchNumber: 26,
    phase: 'group',
    groupLetter: 'B',
    date: '2026-06-18',
    kickoffEt: '15:00',
    homeSlot: 'SUI',
    awaySlot: 'BIH',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 27,
    phase: 'group',
    groupLetter: 'B',
    date: '2026-06-18',
    kickoffEt: '18:00',
    homeSlot: 'CAN',
    awaySlot: 'QAT',
    venue: 'Vancouver',
  },
  {
    fifaMatchNumber: 51,
    phase: 'group',
    groupLetter: 'B',
    date: '2026-06-24',
    kickoffEt: '15:00',
    homeSlot: 'SUI',
    awaySlot: 'CAN',
    venue: 'Vancouver',
  },
  {
    fifaMatchNumber: 52,
    phase: 'group',
    groupLetter: 'B',
    date: '2026-06-24',
    kickoffEt: '15:00',
    homeSlot: 'BIH',
    awaySlot: 'QAT',
    venue: 'Seattle',
  },

  // ── Group C: BRA, MAR, HAI, SCO ──────────────────────────────
  {
    fifaMatchNumber: 5,
    phase: 'group',
    groupLetter: 'C',
    date: '2026-06-13',
    kickoffEt: '21:00',
    homeSlot: 'HAI',
    awaySlot: 'SCO',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 7,
    phase: 'group',
    groupLetter: 'C',
    date: '2026-06-13',
    kickoffEt: '18:00',
    homeSlot: 'BRA',
    awaySlot: 'MAR',
    venue: 'New York/New Jersey',
  },
  {
    fifaMatchNumber: 29,
    phase: 'group',
    groupLetter: 'C',
    date: '2026-06-19',
    kickoffEt: '20:30',
    homeSlot: 'BRA',
    awaySlot: 'HAI',
    venue: 'Philadelphia',
  },
  {
    fifaMatchNumber: 30,
    phase: 'group',
    groupLetter: 'C',
    date: '2026-06-19',
    kickoffEt: '18:00',
    homeSlot: 'SCO',
    awaySlot: 'MAR',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 49,
    phase: 'group',
    groupLetter: 'C',
    date: '2026-06-24',
    kickoffEt: '18:00',
    homeSlot: 'SCO',
    awaySlot: 'BRA',
    venue: 'Miami',
  },
  {
    fifaMatchNumber: 50,
    phase: 'group',
    groupLetter: 'C',
    date: '2026-06-24',
    kickoffEt: '18:00',
    homeSlot: 'MAR',
    awaySlot: 'HAI',
    venue: 'Atlanta',
  },

  // ── Group D: USA, PAR, AUS, TUR ──────────────────────────────
  {
    fifaMatchNumber: 4,
    phase: 'group',
    groupLetter: 'D',
    date: '2026-06-12',
    kickoffEt: '21:00',
    homeSlot: 'USA',
    awaySlot: 'PAR',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 6,
    phase: 'group',
    groupLetter: 'D',
    date: '2026-06-13',
    kickoffEt: '00:00',
    homeSlot: 'AUS',
    awaySlot: 'TUR',
    venue: 'Vancouver',
  },
  {
    fifaMatchNumber: 31,
    phase: 'group',
    groupLetter: 'D',
    date: '2026-06-19',
    kickoffEt: '23:00',
    homeSlot: 'TUR',
    awaySlot: 'PAR',
    venue: 'San Francisco Bay Area',
  },
  {
    fifaMatchNumber: 32,
    phase: 'group',
    groupLetter: 'D',
    date: '2026-06-19',
    kickoffEt: '15:00',
    homeSlot: 'USA',
    awaySlot: 'AUS',
    venue: 'Seattle',
  },
  {
    fifaMatchNumber: 59,
    phase: 'group',
    groupLetter: 'D',
    date: '2026-06-25',
    kickoffEt: '22:00',
    homeSlot: 'TUR',
    awaySlot: 'USA',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 60,
    phase: 'group',
    groupLetter: 'D',
    date: '2026-06-25',
    kickoffEt: '22:00',
    homeSlot: 'PAR',
    awaySlot: 'AUS',
    venue: 'San Francisco Bay Area',
  },

  // ── Group E: GER, CUW, CIV, ECU ──────────────────────────────
  {
    fifaMatchNumber: 9,
    phase: 'group',
    groupLetter: 'E',
    date: '2026-06-14',
    kickoffEt: '19:00',
    homeSlot: 'CIV',
    awaySlot: 'ECU',
    venue: 'Philadelphia',
  },
  {
    fifaMatchNumber: 10,
    phase: 'group',
    groupLetter: 'E',
    date: '2026-06-14',
    kickoffEt: '13:00',
    homeSlot: 'GER',
    awaySlot: 'CUW',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 33,
    phase: 'group',
    groupLetter: 'E',
    date: '2026-06-20',
    kickoffEt: '16:00',
    homeSlot: 'GER',
    awaySlot: 'CIV',
    venue: 'Toronto',
  },
  {
    fifaMatchNumber: 34,
    phase: 'group',
    groupLetter: 'E',
    date: '2026-06-20',
    kickoffEt: '20:00',
    homeSlot: 'ECU',
    awaySlot: 'CUW',
    venue: 'Kansas City',
  },
  {
    fifaMatchNumber: 55,
    phase: 'group',
    groupLetter: 'E',
    date: '2026-06-25',
    kickoffEt: '16:00',
    homeSlot: 'CUW',
    awaySlot: 'CIV',
    venue: 'Philadelphia',
  },
  {
    fifaMatchNumber: 56,
    phase: 'group',
    groupLetter: 'E',
    date: '2026-06-25',
    kickoffEt: '16:00',
    homeSlot: 'ECU',
    awaySlot: 'GER',
    venue: 'New York/New Jersey',
  },

  // ── Group F: NED, JPN, SWE, TUN ──────────────────────────────
  {
    fifaMatchNumber: 11,
    phase: 'group',
    groupLetter: 'F',
    date: '2026-06-14',
    kickoffEt: '16:00',
    homeSlot: 'NED',
    awaySlot: 'JPN',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 12,
    phase: 'group',
    groupLetter: 'F',
    date: '2026-06-14',
    kickoffEt: '22:00',
    homeSlot: 'SWE',
    awaySlot: 'TUN',
    venue: 'Monterrey',
  },
  {
    fifaMatchNumber: 35,
    phase: 'group',
    groupLetter: 'F',
    date: '2026-06-20',
    kickoffEt: '13:00',
    homeSlot: 'NED',
    awaySlot: 'SWE',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 36,
    phase: 'group',
    groupLetter: 'F',
    date: '2026-06-20',
    kickoffEt: '00:00',
    homeSlot: 'TUN',
    awaySlot: 'JPN',
    venue: 'Monterrey',
  },
  {
    fifaMatchNumber: 57,
    phase: 'group',
    groupLetter: 'F',
    date: '2026-06-25',
    kickoffEt: '19:00',
    homeSlot: 'JPN',
    awaySlot: 'SWE',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 58,
    phase: 'group',
    groupLetter: 'F',
    date: '2026-06-25',
    kickoffEt: '19:00',
    homeSlot: 'TUN',
    awaySlot: 'NED',
    venue: 'Kansas City',
  },

  // ── Group G: BEL, EGY, IRN, NZL ──────────────────────────────
  {
    fifaMatchNumber: 15,
    phase: 'group',
    groupLetter: 'G',
    date: '2026-06-15',
    kickoffEt: '21:00',
    homeSlot: 'IRN',
    awaySlot: 'NZL',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 16,
    phase: 'group',
    groupLetter: 'G',
    date: '2026-06-15',
    kickoffEt: '15:00',
    homeSlot: 'BEL',
    awaySlot: 'EGY',
    venue: 'Seattle',
  },
  {
    fifaMatchNumber: 39,
    phase: 'group',
    groupLetter: 'G',
    date: '2026-06-21',
    kickoffEt: '15:00',
    homeSlot: 'BEL',
    awaySlot: 'IRN',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 40,
    phase: 'group',
    groupLetter: 'G',
    date: '2026-06-21',
    kickoffEt: '21:00',
    homeSlot: 'NZL',
    awaySlot: 'EGY',
    venue: 'Vancouver',
  },
  {
    fifaMatchNumber: 63,
    phase: 'group',
    groupLetter: 'G',
    date: '2026-06-26',
    kickoffEt: '23:00',
    homeSlot: 'EGY',
    awaySlot: 'IRN',
    venue: 'Seattle',
  },
  {
    fifaMatchNumber: 64,
    phase: 'group',
    groupLetter: 'G',
    date: '2026-06-26',
    kickoffEt: '23:00',
    homeSlot: 'NZL',
    awaySlot: 'BEL',
    venue: 'Vancouver',
  },

  // ── Group H: ESP, CPV, KSA, URU ──────────────────────────────
  {
    fifaMatchNumber: 13,
    phase: 'group',
    groupLetter: 'H',
    date: '2026-06-15',
    kickoffEt: '18:00',
    homeSlot: 'KSA',
    awaySlot: 'URU',
    venue: 'Miami',
  },
  {
    fifaMatchNumber: 14,
    phase: 'group',
    groupLetter: 'H',
    date: '2026-06-15',
    kickoffEt: '12:00',
    homeSlot: 'ESP',
    awaySlot: 'CPV',
    venue: 'Atlanta',
  },
  {
    fifaMatchNumber: 37,
    phase: 'group',
    groupLetter: 'H',
    date: '2026-06-21',
    kickoffEt: '18:00',
    homeSlot: 'URU',
    awaySlot: 'CPV',
    venue: 'Miami',
  },
  {
    fifaMatchNumber: 38,
    phase: 'group',
    groupLetter: 'H',
    date: '2026-06-21',
    kickoffEt: '12:00',
    homeSlot: 'ESP',
    awaySlot: 'KSA',
    venue: 'Atlanta',
  },
  {
    fifaMatchNumber: 65,
    phase: 'group',
    groupLetter: 'H',
    date: '2026-06-26',
    kickoffEt: '20:00',
    homeSlot: 'CPV',
    awaySlot: 'KSA',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 66,
    phase: 'group',
    groupLetter: 'H',
    date: '2026-06-26',
    kickoffEt: '20:00',
    homeSlot: 'URU',
    awaySlot: 'ESP',
    venue: 'Guadalajara',
  },

  // ── Group I: FRA, SEN, IRQ, NOR ──────────────────────────────
  {
    fifaMatchNumber: 17,
    phase: 'group',
    groupLetter: 'I',
    date: '2026-06-16',
    kickoffEt: '15:00',
    homeSlot: 'FRA',
    awaySlot: 'SEN',
    venue: 'New York/New Jersey',
  },
  {
    fifaMatchNumber: 18,
    phase: 'group',
    groupLetter: 'I',
    date: '2026-06-16',
    kickoffEt: '18:00',
    homeSlot: 'IRQ',
    awaySlot: 'NOR',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 41,
    phase: 'group',
    groupLetter: 'I',
    date: '2026-06-22',
    kickoffEt: '20:00',
    homeSlot: 'NOR',
    awaySlot: 'SEN',
    venue: 'New York/New Jersey',
  },
  {
    fifaMatchNumber: 42,
    phase: 'group',
    groupLetter: 'I',
    date: '2026-06-22',
    kickoffEt: '17:00',
    homeSlot: 'FRA',
    awaySlot: 'IRQ',
    venue: 'Philadelphia',
  },
  {
    fifaMatchNumber: 61,
    phase: 'group',
    groupLetter: 'I',
    date: '2026-06-26',
    kickoffEt: '15:00',
    homeSlot: 'NOR',
    awaySlot: 'FRA',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 62,
    phase: 'group',
    groupLetter: 'I',
    date: '2026-06-26',
    kickoffEt: '15:00',
    homeSlot: 'SEN',
    awaySlot: 'IRQ',
    venue: 'Toronto',
  },

  // ── Group J: ARG, ALG, AUT, JOR ──────────────────────────────
  {
    fifaMatchNumber: 19,
    phase: 'group',
    groupLetter: 'J',
    date: '2026-06-16',
    kickoffEt: '21:00',
    homeSlot: 'ARG',
    awaySlot: 'ALG',
    venue: 'Kansas City',
  },
  {
    fifaMatchNumber: 20,
    phase: 'group',
    groupLetter: 'J',
    date: '2026-06-16',
    kickoffEt: '00:00',
    homeSlot: 'AUT',
    awaySlot: 'JOR',
    venue: 'San Francisco Bay Area',
  },
  {
    fifaMatchNumber: 43,
    phase: 'group',
    groupLetter: 'J',
    date: '2026-06-22',
    kickoffEt: '13:00',
    homeSlot: 'ARG',
    awaySlot: 'AUT',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 44,
    phase: 'group',
    groupLetter: 'J',
    date: '2026-06-22',
    kickoffEt: '23:00',
    homeSlot: 'JOR',
    awaySlot: 'ALG',
    venue: 'San Francisco Bay Area',
  },
  {
    fifaMatchNumber: 69,
    phase: 'group',
    groupLetter: 'J',
    date: '2026-06-27',
    kickoffEt: '22:00',
    homeSlot: 'ALG',
    awaySlot: 'AUT',
    venue: 'Kansas City',
  },
  {
    fifaMatchNumber: 70,
    phase: 'group',
    groupLetter: 'J',
    date: '2026-06-27',
    kickoffEt: '22:00',
    homeSlot: 'JOR',
    awaySlot: 'ARG',
    venue: 'Dallas',
  },

  // ── Group K: POR, COD, UZB, COL ──────────────────────────────
  {
    fifaMatchNumber: 23,
    phase: 'group',
    groupLetter: 'K',
    date: '2026-06-17',
    kickoffEt: '13:00',
    homeSlot: 'POR',
    awaySlot: 'COD',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 24,
    phase: 'group',
    groupLetter: 'K',
    date: '2026-06-17',
    kickoffEt: '22:00',
    homeSlot: 'UZB',
    awaySlot: 'COL',
    venue: 'Mexico City',
  },
  {
    fifaMatchNumber: 47,
    phase: 'group',
    groupLetter: 'K',
    date: '2026-06-23',
    kickoffEt: '13:00',
    homeSlot: 'POR',
    awaySlot: 'UZB',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 48,
    phase: 'group',
    groupLetter: 'K',
    date: '2026-06-23',
    kickoffEt: '22:00',
    homeSlot: 'COL',
    awaySlot: 'COD',
    venue: 'Guadalajara',
  },
  {
    fifaMatchNumber: 71,
    phase: 'group',
    groupLetter: 'K',
    date: '2026-06-27',
    kickoffEt: '19:30',
    homeSlot: 'COL',
    awaySlot: 'POR',
    venue: 'Miami',
  },
  {
    fifaMatchNumber: 72,
    phase: 'group',
    groupLetter: 'K',
    date: '2026-06-27',
    kickoffEt: '19:30',
    homeSlot: 'COD',
    awaySlot: 'UZB',
    venue: 'Atlanta',
  },

  // ── Group L: ENG, CRO, GHA, PAN ──────────────────────────────
  {
    fifaMatchNumber: 21,
    phase: 'group',
    groupLetter: 'L',
    date: '2026-06-17',
    kickoffEt: '19:00',
    homeSlot: 'GHA',
    awaySlot: 'PAN',
    venue: 'Toronto',
  },
  {
    fifaMatchNumber: 22,
    phase: 'group',
    groupLetter: 'L',
    date: '2026-06-17',
    kickoffEt: '16:00',
    homeSlot: 'ENG',
    awaySlot: 'CRO',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 45,
    phase: 'group',
    groupLetter: 'L',
    date: '2026-06-23',
    kickoffEt: '16:00',
    homeSlot: 'ENG',
    awaySlot: 'GHA',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 46,
    phase: 'group',
    groupLetter: 'L',
    date: '2026-06-23',
    kickoffEt: '19:00',
    homeSlot: 'PAN',
    awaySlot: 'CRO',
    venue: 'Toronto',
  },
  {
    fifaMatchNumber: 67,
    phase: 'group',
    groupLetter: 'L',
    date: '2026-06-27',
    kickoffEt: '17:00',
    homeSlot: 'PAN',
    awaySlot: 'ENG',
    venue: 'New York/New Jersey',
  },
  {
    fifaMatchNumber: 68,
    phase: 'group',
    groupLetter: 'L',
    date: '2026-06-27',
    kickoffEt: '17:00',
    homeSlot: 'CRO',
    awaySlot: 'GHA',
    venue: 'Philadelphia',
  },

  // ── Round of 32 ───────────────────────────────────────────────
  {
    fifaMatchNumber: 73,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-28',
    kickoffEt: '15:00',
    homeSlot: '2A',
    awaySlot: '2B',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 74,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-29',
    kickoffEt: '16:30',
    homeSlot: '1E',
    awaySlot: '3ABCDF',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 75,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-29',
    kickoffEt: '21:00',
    homeSlot: '1F',
    awaySlot: '2C',
    venue: 'Monterrey',
  },
  {
    fifaMatchNumber: 76,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-29',
    kickoffEt: '13:00',
    homeSlot: '1C',
    awaySlot: '2F',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 77,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-30',
    kickoffEt: '17:00',
    homeSlot: '1I',
    awaySlot: '3CDFGH',
    venue: 'New York/New Jersey',
  },
  {
    fifaMatchNumber: 78,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-30',
    kickoffEt: '13:00',
    homeSlot: '2E',
    awaySlot: '2I',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 79,
    phase: 'r32',
    groupLetter: null,
    date: '2026-06-30',
    kickoffEt: '21:00',
    homeSlot: '1A',
    awaySlot: '3CEFHI',
    venue: 'Mexico City',
  },
  {
    fifaMatchNumber: 80,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-01',
    kickoffEt: '12:00',
    homeSlot: '1L',
    awaySlot: '3EHIJK',
    venue: 'Atlanta',
  },
  {
    fifaMatchNumber: 81,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-01',
    kickoffEt: '20:00',
    homeSlot: '1D',
    awaySlot: '3BEFIJ',
    venue: 'San Francisco Bay Area',
  },
  {
    fifaMatchNumber: 82,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-01',
    kickoffEt: '16:00',
    homeSlot: '1G',
    awaySlot: '3AEHIJ',
    venue: 'Seattle',
  },
  {
    fifaMatchNumber: 83,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-02',
    kickoffEt: '19:00',
    homeSlot: '2K',
    awaySlot: '2L',
    venue: 'Toronto',
  },
  {
    fifaMatchNumber: 84,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-02',
    kickoffEt: '15:00',
    homeSlot: '1H',
    awaySlot: '2J',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 85,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-02',
    kickoffEt: '23:00',
    homeSlot: '1B',
    awaySlot: '3EFGIJ',
    venue: 'Vancouver',
  },
  {
    fifaMatchNumber: 86,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-03',
    kickoffEt: '18:00',
    homeSlot: '1J',
    awaySlot: '2H',
    venue: 'Miami',
  },
  {
    fifaMatchNumber: 87,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-03',
    kickoffEt: '21:30',
    homeSlot: '1K',
    awaySlot: '3DEIJL',
    venue: 'Kansas City',
  },
  {
    fifaMatchNumber: 88,
    phase: 'r32',
    groupLetter: null,
    date: '2026-07-03',
    kickoffEt: '14:00',
    homeSlot: '2D',
    awaySlot: '2G',
    venue: 'Dallas',
  },

  // ── Round of 16 ───────────────────────────────────────────────
  {
    fifaMatchNumber: 89,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-04',
    kickoffEt: '17:00',
    homeSlot: 'W74',
    awaySlot: 'W77',
    venue: 'Philadelphia',
  },
  {
    fifaMatchNumber: 90,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-04',
    kickoffEt: '13:00',
    homeSlot: 'W73',
    awaySlot: 'W75',
    venue: 'Houston',
  },
  {
    fifaMatchNumber: 91,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-05',
    kickoffEt: '16:00',
    homeSlot: 'W76',
    awaySlot: 'W78',
    venue: 'New York/New Jersey',
  },
  {
    fifaMatchNumber: 92,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-05',
    kickoffEt: '20:00',
    homeSlot: 'W79',
    awaySlot: 'W80',
    venue: 'Mexico City',
  },
  {
    fifaMatchNumber: 93,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-06',
    kickoffEt: '15:00',
    homeSlot: 'W83',
    awaySlot: 'W84',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 94,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-06',
    kickoffEt: '20:00',
    homeSlot: 'W81',
    awaySlot: 'W82',
    venue: 'Seattle',
  },
  {
    fifaMatchNumber: 95,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-07',
    kickoffEt: '12:00',
    homeSlot: 'W86',
    awaySlot: 'W88',
    venue: 'Atlanta',
  },
  {
    fifaMatchNumber: 96,
    phase: 'r16',
    groupLetter: null,
    date: '2026-07-07',
    kickoffEt: '16:00',
    homeSlot: 'W85',
    awaySlot: 'W87',
    venue: 'Vancouver',
  },

  // ── Quarter-finals ────────────────────────────────────────────
  {
    fifaMatchNumber: 97,
    phase: 'qf',
    groupLetter: null,
    date: '2026-07-09',
    kickoffEt: '16:00',
    homeSlot: 'W89',
    awaySlot: 'W90',
    venue: 'Boston',
  },
  {
    fifaMatchNumber: 98,
    phase: 'qf',
    groupLetter: null,
    date: '2026-07-10',
    kickoffEt: '15:00',
    homeSlot: 'W93',
    awaySlot: 'W94',
    venue: 'Los Angeles',
  },
  {
    fifaMatchNumber: 99,
    phase: 'qf',
    groupLetter: null,
    date: '2026-07-11',
    kickoffEt: '17:00',
    homeSlot: 'W91',
    awaySlot: 'W92',
    venue: 'Miami',
  },
  {
    fifaMatchNumber: 100,
    phase: 'qf',
    groupLetter: null,
    date: '2026-07-11',
    kickoffEt: '21:00',
    homeSlot: 'W95',
    awaySlot: 'W96',
    venue: 'Kansas City',
  },

  // ── Semi-finals ───────────────────────────────────────────────
  {
    fifaMatchNumber: 101,
    phase: 'sf',
    groupLetter: null,
    date: '2026-07-14',
    kickoffEt: '15:00',
    homeSlot: 'W97',
    awaySlot: 'W98',
    venue: 'Dallas',
  },
  {
    fifaMatchNumber: 102,
    phase: 'sf',
    groupLetter: null,
    date: '2026-07-15',
    kickoffEt: '15:00',
    homeSlot: 'W99',
    awaySlot: 'W100',
    venue: 'Atlanta',
  },

  // ── Bronze final ──────────────────────────────────────────────
  {
    fifaMatchNumber: 103,
    phase: 'third',
    groupLetter: null,
    date: '2026-07-18',
    kickoffEt: '17:00',
    homeSlot: 'RU101',
    awaySlot: 'RU102',
    venue: 'Miami',
  },

  // ── Final ─────────────────────────────────────────────────────
  {
    fifaMatchNumber: 104,
    phase: 'final',
    groupLetter: null,
    date: '2026-07-19',
    kickoffEt: '15:00',
    homeSlot: 'W101',
    awaySlot: 'W102',
    venue: 'New York/New Jersey',
  },
];
